package calculator_module;


/**
* calculator_module/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Monday, 11 May, 2026 8:47:08 AM IST
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
  int subtract (int a, int b);
  int multiply (int a, int b);
  int divide (int a, int b);
  void shutdown ();
} // interface CalculatorOperations
